language: node_js
node_js: 
  - "node"
  - "10"
  - "8"
services: mongodb
cache:  
  directories:
    - "node_modules"
before_install:
  - npm install -g codecov
before_script:
  - npm update
script:
  - npm run test-ci